# Generated by Django 4.2.14 on 2024-08-08 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'booking_time', 'table_booked'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('18:00', '6 PM'), ('19:00', '7 PM'), ('20:00', '8 PM'), ('21:00', '9 PM'), ('22:00', '10 PM'), ('23:00', '11 PM'), ('00:00', '12 AM'), ('01:00', '1 AM'), ('02:00', '2 AM'), ('03:00', '3 AM'), ('04:00', '4 AM'), ('05:00', '5 AM')], default='6 PM', max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_booked',
            field=models.CharField(choices=[('1', 'Table 1'), ('2', 'Table 2'), ('3', 'Table 3')], default='1'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time', 'table_booked', 'user')},
        ),
        migrations.DeleteModel(
            name='CafeTable',
        ),
    ]
