# Generated by Django 4.2.14 on 2024-08-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_booking_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time', 'table_booked')},
        ),
    ]
